# Generated by Django 4.2.4 on 2023-10-07 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryForChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid1, max_length=264, unique=True)),
                ('title', models.CharField(max_length=264, verbose_name='Put a Title')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(verbose_name='Write a short descriptio of this story')),
                ('Story_content', models.TextField(verbose_name='Tell your story...')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_story_author', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(related_name='genre_vote_stories', to='core_app.genre')),
            ],
        ),
        migrations.CreateModel(
            name='StoryWriteUpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_line', models.TextField(verbose_name='Story line of the WriteUp')),
                ('max_slots', models.IntegerField(blank=True, null=True)),
                ('dead_line', models.DateField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoteForStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('stories', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='genre_vote_stories', to='archive_vote.storyforchallenge')),
                ('voter', models.ManyToManyField(related_name='voterr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_archive', to=settings.AUTH_USER_MODEL)),
                ('stories', models.ManyToManyField(related_name='stories_archive', to='core_app.stories')),
            ],
        ),
        migrations.CreateModel(
            name='EmeraldList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stories', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emerald_stories', to='archive_vote.storyforchallenge')),
            ],
        ),
    ]
